name = "Zaim_Zola"
description = "Heartful Zola theme"
license = "MIT"
homepage = "https://github.com/pinnnosuke/zaim_zola"
min_version = "0.4.0"

[extra]
home_subtitle = "Some profound and catchy statement"

footer_copyright = ''

zaim_menu = [
    { link = "/posts", name = "Posts" },
    { link = "/about", name = "About" }
]

zaim_social = [
    { name = "twitter", link = "https://twitter.com" },
    { name = "github", link = "https://github.com" },
    { name = "email", link = "mailto:name@domain.com" }
]

[author]
name = "pinnosuke"
homepage = "https://github.io/pinnosuke/"
repo = "https://github.com/pinnosuke/zaim_zola"

[original]
author = "VersBinarii"
repo = "https://github.com/VersBinarii/hermit_zola"
